name: Java CI with Maven - Test and package

# Ce workflow se déclenche lorsqu'une pull request est ouverte vers la branche main
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Java Project
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout - Se place dans le dépôt courant
      - name: Checkout repository
        uses: actions/checkout@v4
	with:
    	  ref: dev
      # Étape 2 : Setup Java - Configure Java avec la version 21 et la distribution corretto
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # Étape 3 : Build avec Maven - Construction et test du projet avec Maven
      - name: Build and Test with Maven
        run: mvn -B package

